#!/usr/bin/env python3
"""
Geocode the SF recommendations for the interactive map.

Reads scripts/sf_places_input.json, looks up coordinates via OpenStreetMap's
Nominatim service, and writes data/sf_places.js (loaded by the page via a
<script> tag) plus data/sf_places.json.

Results are cached in scripts/.geocode_cache.json so re-runs are fast and only
new/changed queries hit the network. Standard library only (Python 3.9+).

Usage:
    python3 scripts/geocode_places.py

Nominatim usage policy: max 1 request/second, descriptive User-Agent. Please
don't crank the rate up.
"""

import json
import os
import sys
import time
import urllib.parse
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DATA_DIR = os.path.join(ROOT, "data")
INPUT = os.path.join(HERE, "sf_places_input.json")
CACHE = os.path.join(HERE, ".geocode_cache.json")

UA = "ucsf-bmi-orientation-map/1.0 (student orientation site; contact program staff)"
# Bias results toward the SF Bay Area (left,top,right,bottom) without hard-bounding,
# so Oakland/Marin picks still resolve.
VIEWBOX = "-122.55,37.86,-122.32,37.70"


def load_json(path, default=None):
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as fh:
            return json.load(fh)
    return default


def geocode(query):
    params = urllib.parse.urlencode({
        "format": "json", "limit": "1", "q": query,
        "viewbox": VIEWBOX, "bounded": "0",
    })
    url = "https://nominatim.openstreetmap.org/search?" + params
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as resp:
        data = json.loads(resp.read().decode("utf-8"))
    if not data:
        return None
    hit = data[0]
    return {
        "lat": round(float(hit["lat"]), 6),
        "lng": round(float(hit["lon"]), 6),
        "matched": hit.get("display_name", ""),
    }


def main():
    cfg = load_json(INPUT)
    if not cfg or "places" not in cfg:
        print(f"No places found in {INPUT}", file=sys.stderr)
        sys.exit(1)
    places = cfg["places"]
    cache = load_json(CACHE, {}) or {}

    stats = {"calls": 0}

    def lookup(query):
        """Cached geocode; only hits the network (and rate-limits) on a cache miss."""
        if query in cache:
            return cache[query]
        try:
            geo = geocode(query)
        except Exception as exc:  # noqa: BLE001
            print(f"  ! request failed for '{query}' ({exc})", file=sys.stderr)
            geo = None
        cache[query] = geo
        stats["calls"] += 1
        time.sleep(1.1)  # Nominatim rate limit
        return geo

    out, failures = [], []
    for p in places:
        name = p.get("name", "").strip()
        if not name:
            continue
        rec = {"name": name, "cat": p.get("cat", "spot"), "note": p.get("note", "")}

        primary = p.get("q") or f"{name}, San Francisco, CA"
        fallback = f"{name}, San Francisco, CA"
        geo = lookup(primary)
        if not geo and fallback != primary:
            geo = lookup(fallback)  # retry with a simpler query

        if geo:
            rec.update(geo)
            print(f"  · {name} -> {geo['lat']},{geo['lng']}", file=sys.stderr)
        else:
            rec.update({"lat": None, "lng": None, "matched": ""})
            failures.append(name)
        out.append(rec)

    network_calls = stats["calls"]

    # persist cache
    with open(CACHE, "w", encoding="utf-8") as fh:
        json.dump(cache, fh, indent=2, ensure_ascii=False)

    located = [r for r in out if r["lat"] is not None]
    payload = {"count": len(located), "total": len(out), "items": out}

    os.makedirs(DATA_DIR, exist_ok=True)
    with open(os.path.join(DATA_DIR, "sf_places.json"), "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=2, ensure_ascii=False)
    banner = "/* AUTO-GENERATED by scripts/geocode_places.py — do not edit by hand. */\n"
    with open(os.path.join(DATA_DIR, "sf_places.js"), "w", encoding="utf-8") as fh:
        fh.write(banner + "window.SF_PLACES = " + json.dumps(payload, ensure_ascii=False, indent=2) + ";\n")

    print(f"\nGeocoded {len(located)}/{len(out)} places "
          f"({network_calls} new network lookups, rest cached).", file=sys.stderr)
    if failures:
        print("Could NOT locate (add/fix the 'q' hint in sf_places_input.json):", file=sys.stderr)
        for f in failures:
            print(f"   - {f}", file=sys.stderr)


if __name__ == "__main__":
    main()
